name: 'ghsemver'
description: 'Calculate semantic version based on GitHub commit history and Conventional Commits'
author: 'shared-utils'

branding:
  icon: 'tag'
  color: 'blue'

inputs:
  command:
    description: 'Command to run: current or next'
    required: true
    default: 'next'
  branch:
    description: 'Branch name (optional, auto-detected if not provided)'
    required: false
  main-branch:
    description: 'Main branch name (optional, auto-detected if not provided)'
    required: false
  suffix:
    description: 'Prerelease suffix for non-main branches (optional, uses branch name if not provided)'
    required: false
  log:
    description: 'Enable verbose logging'
    required: false
    default: 'false'

outputs:
  version:
    description: 'The calculated version number'

runs:
  using: 'node20'
  main: 'dist/action.js'

